<?php
/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
return function($container) {
    $instance = new \Tworzenieweb\UserBundle\Controller\DefaultController();
    return $instance;
};
