#parameters:
#    vendor_security.authentication_handler: Tworzenieweb\UserBundle\Handler\AuthenticationHandler
#
#services:
#    authentication_handler:
#        class:  %vendor_security.authentication_handler%
#        arguments:  [@router]
#        tags:
#            - { name: 'monolog.logger', channel: 'security' }